name: Static Type Check

on:
  workflow_call:
    inputs:
      package:
        description: 'Name of the Python package.'
        required: true
        type: string
      python_version:
        description: 'Python version.'
        required: false
        default: '3.10'
        type: string
      artifact:
        description: 'Name of the coverage artifact.'
        required: true
        type: string

jobs:

  StaticTypeCheck:
    name: 👀 Check Static Typing using Python ${{ inputs.python_version }}
    runs-on: ubuntu-latest

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v2

      - name: 🐍 Setup Python ${{ inputs.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}

      - name: 🗂 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Check Static Typing
        continue-on-error: true
        run: |
          pwd
          mypy --html-report htmlmypy -m ${{ inputs.package }}

      - name: 📤 Upload 'Static Typing Report' artifact
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact }}
          path: htmlmypy
          if-no-files-found: error
          retention-days: 1
