name: Static Type Check

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version.'
        required: false
        default: '3.10'
        type: string
      requirements:
        description: 'Python dependencies to be installed through pip.'
        required: false
        default: '-r tests/requirements.txt'
        type: string
      html_report:
        description: 'Directory for --html-report.'
        required: false
        default: 'htmlmypy'
        type: string
      mypy_args:
        description: 'Arguments to mypy, except the HTML report (see option html_report).'
        required: true
        type: string
      artifact:
        description: 'Name of the coverage artifact.'
        required: true
        type: string

jobs:

  StaticTypeCheck:
    name: 👀 Check Static Typing using Python ${{ inputs.python_version }}
    runs-on: ubuntu-latest

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v2

      - name: 🐍 Setup Python ${{ inputs.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}

      - name: 🗂 Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install ${{ inputs.requirements }}

      - name: Check Static Typing
        continue-on-error: true
        run: |
          [ 'x${{ inputs.html_report }}' != 'x' ] && MYPY_HTML='--html-report=${{ inputs.html_report }}' || unset MYPY_HTML
          mypy $MYPY_HTML ${{ inputs.mypy_args }}

      - name: 📤 Upload 'Static Typing Report' artifact
        if: ${{ inputs.html_report != '' }}
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.html_report }}
          if-no-files-found: error
          retention-days: 1
